// Every asset path and cross-module object name Colin's training modules read or
// write. M1 and M2 each used to declare their own identical copy of the folder
// constants, and M2 rebuilt the PM8000_Training.prefab path from its own copy — so
// the cross-module dependency had no compiler linkage and a folder move would have
// broken it silently. This is the one place the two builders meet.
internal static class Colin_Training_Paths{
    public const string Root = "Assets/Members/Colin";
    public const string ScenesDir = Root + "/Scenes";
    public const string TrainingDir = Root + "/Training";
    public const string PrefabsDir = TrainingDir + "/Prefabs";
    public const string LessonsDir = TrainingDir + "/Lessons";

    public const string M1LessonPath = LessonsDir + "/M1_Lesson.asset";
    public const string M2LessonPath = LessonsDir + "/M2_Lesson.asset";
    public const string Module1ScenePath = ScenesDir + "/Module1_Overview.unity";
    public const string Module2ScenePath = ScenesDir + "/Module2_Startup.unity";

    // Written by Training/3 (M1). Both module scenes hold a prefab instance of it,
    // so it is a shared asset now rather than a build-order dependency — rebuilding
    // M1 rewrites it under M2's feet.
    public const string MillTrainingPrefabPath = PrefabsDir + "/PM8000_Training.prefab";
    public const string DemoBlockPrefabPath = PrefabsDir + "/Demo_Block.prefab";

    // Scene object names looked up by string across module or menu-command boundaries.
    public const string MillWrapperName = "PM8000_Training";
    public const string DemoBlockName = "Demo_Block";
    public const string ViceName = "Vice";
    public const string MarkerGroupName = "Component_Markers";

    // Source art — authored elsewhere, never generated by a builder.
    public const string MillPrefabPath = "Assets/Prefabs/reconstructedPM8000.prefab";
    public const string VicePrefabPath = "Assets/Game_Objects/Extra/DualAxisVice.prefab";
    public const string DeskPrefabPath = "Assets/Game_Objects/PCTable.prefab";
    public const string BlueGlassPath = "Assets/Materials/Blue_Glass.mat";
}
